# Generated by Django 3.2.21 on 2023-10-06 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_auto_20231006_0829"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="recipe",
            managers=[],
        ),
    ]
